/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : Document Properties
 #	author : miyako
 #	2013/02/27
 #
 # --------------------------------------------------------------------------------*/



// --- Files and Folders
void PATH_Get_creation_date(sLONG_PTR *pResult, PackagePtr pParams);
void PATH_Set_modification_date(sLONG_PTR *pResult, PackagePtr pParams);
void PATH_Get_modification_date(sLONG_PTR *pResult, PackagePtr pParams);
void PATH_Set_creation_date(sLONG_PTR *pResult, PackagePtr pParams);
void PATH_Get_access_date(sLONG_PTR *pResult, PackagePtr pParams);
void PATH_Set_access_date(sLONG_PTR *pResult, PackagePtr pParams);
void PATH_Get_hidden(sLONG_PTR *pResult, PackagePtr pParams);
void PATH_Set_hidden(sLONG_PTR *pResult, PackagePtr pParams);
